FROM python:3.12

RUN apt update &&\
    apt install -y git openssh-client curl gnupg2 postgresql-client --no-install-recommends &&\
    apt clean && rm -rf /var/lib/apt/lists/*

COPY requirements*txt .

RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt -r requirements.dev.txt

EXPOSE 8000

WORKDIR /workspace