services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-workspace
    volumes:
      - .:/workspace:cached
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true
  db:
    image: postgres
    container_name: dev-postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}