FROM python:3.12

WORKDIR /api_gateway

RUN apt update &&\
    apt install -y git openssh-client postgresql-client --no-install-recommends &&\
    apt clean && rm -rf /var/lib/apt/lists/*

COPY . .

RUN python -m pip install -U pip && \
    python -m pip install -r requirements.txt

EXPOSE 8000

SHELL ["/bin/bash", "-c"]
CMD uvicorn app.main:app --host 0.0.0.0 --port 8000