"""change type order subunit

Revision ID: 1713f8a5a28b
Revises: 4fa82ecfcfb4
Create Date: 2025-08-04 23:44:25.250032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1713f8a5a28b'
down_revision: Union[str, Sequence[str], None] = '4fa82ecfcfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """ALTER TABLE subunits 
        ALTER COLUMN "order" 
        TYPE INTEGER 
        USING "order"::INTEGER
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE subunits 
        ALTER COLUMN "order" 
        TYPE VARCHAR 
        USING "order"::VARCHAR"""
    )
    # ### end Alembic commands ###
