"""subunit blocks

Revision ID: 325807dcf81e
Revises: 1713f8a5a28b
Create Date: 2025-08-06 20:31:00.986985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '325807dcf81e'
down_revision: Union[str, Sequence[str], None] = '1713f8a5a28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subunits', sa.Column('blocks', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('subunits', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subunits', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subunits', 'blocks')
    # ### end Alembic commands ###
