"""change name attribute exercise

Revision ID: 325f9378ff71
Revises: 325807dcf81e
Create Date: 2025-08-10 14:45:57.220630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325f9378ff71'
down_revision: Union[str, Sequence[str], None] = '325807dcf81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('exercise_schema', sa.String(), nullable=False))
    op.alter_column('exercises', 'test_cases',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('exercises', 'expected_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('expected_output', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('exercises', 'test_cases',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('exercises', 'exercise_schema')
    # ### end Alembic commands ###
