"""unique_constraint

Revision ID: 4f4f771b6d6e
Revises: 32facb72ffe1
Create Date: 2025-09-02 18:56:18.128980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4f771b6d6e'
down_revision: Union[str, Sequence[str], None] = '32facb72ffe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_quiz', 'quiz_passes', ['user_id', 'quiz_id'])
    op.create_unique_constraint('uix_user_exercise', 'submissions', ['user_id', 'exercise_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_exercise', 'submissions', type_='unique')
    op.drop_constraint('uix_user_quiz', 'quiz_passes', type_='unique')
    # ### end Alembic commands ###
